/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getAlternatives(), "rule__Model__Alternatives");
			builder.put(grammarAccess.getMyObjectAccess().getGroup(), "rule__MyObject__Group__0");
			builder.put(grammarAccess.getMyPortAccess().getGroup(), "rule__MyPort__Group__0");
			builder.put(grammarAccess.getModelAccess().getMyObjectAssignment_0(), "rule__Model__MyObjectAssignment_0");
			builder.put(grammarAccess.getModelAccess().getMyPortAssignment_1(), "rule__Model__MyPortAssignment_1");
			builder.put(grammarAccess.getMyObjectAccess().getNameAssignment_1(), "rule__MyObject__NameAssignment_1");
			builder.put(grammarAccess.getMyObjectAccess().getImportPathAssignment_3(), "rule__MyObject__ImportPathAssignment_3");
			builder.put(grammarAccess.getMyPortAccess().getObjectAssignment_0(), "rule__MyPort__ObjectAssignment_0");
			builder.put(grammarAccess.getMyPortAccess().getPortAssignment_2(), "rule__MyPort__PortAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
