/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getAlternatives(), "rule__Model__Alternatives");
					put(grammarAccess.getMyObjectAccess().getGroup(), "rule__MyObject__Group__0");
					put(grammarAccess.getMyPortAccess().getGroup(), "rule__MyPort__Group__0");
					put(grammarAccess.getModelAccess().getMyObjectAssignment_0(), "rule__Model__MyObjectAssignment_0");
					put(grammarAccess.getModelAccess().getMyPortAssignment_1(), "rule__Model__MyPortAssignment_1");
					put(grammarAccess.getMyObjectAccess().getNameAssignment_1(), "rule__MyObject__NameAssignment_1");
					put(grammarAccess.getMyObjectAccess().getImportPathAssignment_3(), "rule__MyObject__ImportPathAssignment_3");
					put(grammarAccess.getMyPortAccess().getObjectAssignment_0(), "rule__MyPort__ObjectAssignment_0");
					put(grammarAccess.getMyPortAccess().getPortAssignment_2(), "rule__MyPort__PortAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
