/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getMyObject <em>My Object</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Model#getMyPort <em>My Port</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>My Object</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.MyObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>My Object</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_MyObject()
   * @model containment="true"
   * @generated
   */
  EList<MyObject> getMyObject();

  /**
   * Returns the value of the '<em><b>My Port</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.MyPort}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>My Port</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getModel_MyPort()
   * @model containment="true"
   * @generated
   */
  EList<MyPort> getMyPort();

} // Model
