/**
 * generated by Xtext 2.17.1
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>My Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MyObject#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.MyObject#getImportPath <em>Import Path</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMyObject()
 * @model
 * @generated
 */
public interface MyObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMyObject_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MyObject#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Import Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Path</em>' attribute.
   * @see #setImportPath(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMyObject_ImportPath()
   * @model
   * @generated
   */
  String getImportPath();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.MyObject#getImportPath <em>Import Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import Path</em>' attribute.
   * @see #getImportPath()
   * @generated
   */
  void setImportPath(String value);

} // MyObject
